version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - laravel_network
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: gudang_db
      MYSQL_ROOT_PASSWORD: passwordrahasia
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network
networks:
  laravel_network:
    driver: bridge
volumes:
  db_data: